/**
* @generated by vite-plugin-kiru — do not edit
*/
import {
  createRoute,
  createRouteTree,
} from "kiru/router"

export { routes, type AppRoute }

type AppRoute =
  | "/"
  | "/about"
  | "/c/[slug]"
  | "/c/[slug]/submit"
  | "/dev/errors"
  | "/login"
  | "/p/[id]"
  | "/settings"
  | "/u/[username]"

const routes = createRouteTree({
  config: () => import("./pages/scope.config"),
  layout: () => import("./pages/layout"),
  notFound: () => import("./pages/not-found"),
  error: () => import("./pages/error"),
  children: [
    createRoute("/", {
      config: () => import("./pages/page.config"),
      component: () => import("./pages/page"),
    }),
    createRoute("/about", {
      config: () => import("./pages/about/page.config"),
      component: () => import("./pages/about/page"),
    }),
    createRoute("/c/[slug]", {
      config: () => import("./pages/c/[slug]/page.config"),
      component: () => import("./pages/c/[slug]/page"),
    }),
    createRoute("/c/[slug]/submit", {
      config: () => import("./pages/c/[slug]/submit/page.config"),
      component: () => import("./pages/c/[slug]/submit/page"),
    }),
    createRoute("/dev/errors", {
      config: () => import("./pages/dev/errors/page.config"),
      component: () => import("./pages/dev/errors/page"),
    }),
    createRoute("/login", {
      config: () => import("./pages/login/page.config"),
      component: () => import("./pages/login/page"),
    }),
    createRoute("/p/[id]", {
      config: () => import("./pages/p/[id]/page.config"),
      component: () => import("./pages/p/[id]/page"),
    }),
    createRoute("/settings", {
      config: () => import("./pages/settings/page.config"),
      component: () => import("./pages/settings/page"),
    }),
    createRoute("/u/[username]", {
      config: () => import("./pages/u/[username]/page.config"),
      component: () => import("./pages/u/[username]/page"),
    }),
  ],
})

declare module "kiru/router" {
  interface RouteTree {
    routes: AppRoute
  }
}
