/**
* @generated by vite-plugin-kiru — do not edit
*/
import {
  createRoute,
  createRouteTree,
  resolveRouteConfig,
} from "kiru/router"
import * as __cfg_0 from "./pages/page.config"
import * as __cfg_1 from "./pages/about/page.config"
import * as __cfg_2 from "./pages/c/[slug]/page.config"
import * as __cfg_3 from "./pages/c/[slug]/submit/page.config"
import * as __cfg_4 from "./pages/dev/errors/page.config"
import * as __cfg_5 from "./pages/login/page.config"
import * as __cfg_6 from "./pages/p/[id]/page.config"
import * as __cfg_7 from "./pages/settings/page.config"
import * as __cfg_8 from "./pages/u/[username]/page.config"
import * as __cfg_9 from "./pages/scope.config"

export { routes, type PageRoute }

type PageRoute =
  | "/"
  | "/about"
  | "/c/[slug]"
  | "/c/[slug]/submit"
  | "/dev/errors"
  | "/login"
  | "/p/[id]"
  | "/settings"
  | "/u/[username]"

const r0 = createRoute("/", {
    ...resolveRouteConfig(__cfg_0),
    component: () => import("./pages/page"),
  }),
  r1 = createRoute("/about", {
    ...resolveRouteConfig(__cfg_1),
    component: () => import("./pages/about/page"),
  }),
  r2 = createRoute("/c/[slug]", {
    ...resolveRouteConfig(__cfg_2),
    component: () => import("./pages/c/[slug]/page"),
  }),
  r3 = createRoute("/c/[slug]/submit", {
    ...resolveRouteConfig(__cfg_3),
    component: () => import("./pages/c/[slug]/submit/page"),
  }),
  r4 = createRoute("/dev/errors", {
    ...resolveRouteConfig(__cfg_4),
    component: () => import("./pages/dev/errors/page"),
  }),
  r5 = createRoute("/login", {
    ...resolveRouteConfig(__cfg_5),
    component: () => import("./pages/login/page"),
  }),
  r6 = createRoute("/p/[id]", {
    ...resolveRouteConfig(__cfg_6),
    component: () => import("./pages/p/[id]/page"),
  }),
  r7 = createRoute("/settings", {
    ...resolveRouteConfig(__cfg_7),
    component: () => import("./pages/settings/page"),
  }),
  r8 = createRoute("/u/[username]", {
    ...resolveRouteConfig(__cfg_8),
    component: () => import("./pages/u/[username]/page"),
  }),
  routes = createRouteTree({
    ...resolveRouteConfig(__cfg_9),
    layout: () => import("./pages/layout"),
    notFound: () => import("./pages/not-found"),
    error: () => import("./pages/error"),
    children: [r0, r1, r2, r3, r4, r5, r6, r7, r8],
  })

declare module "kiru/router" {
  interface RouteTree {
    routes: [typeof r0, typeof r1, typeof r2, typeof r3, typeof r4, typeof r5, typeof r6, typeof r7, typeof r8]
  }
}
