/**
 * @generated by vite-plugin-kiru — do not edit
 */
import { createRoute, createRouteScope, createRouteTree } from "kiru/router"

export { routes, type AppRoute }

type AppRoute = "/" | "/about" | "/guarded"

const routes = createRouteTree({
  layout: () => import("./pages/layout"),
  children: [
    createRoute("/", () => import("./pages/page")),
    createRoute("/about", () => import("./pages/about/page")),
    createRouteScope({
      config: () => import("./pages/guarded/scope.config"),
      children: [createRoute("/guarded", () => import("./pages/guarded/page"))],
    }),
  ],
})
