/**
* @generated by vite-plugin-kiru — do not edit
*/
import {
  createRoute,
  createRouteScope,
  createRouteTree,
  collectRouteMiddlewareModule,
} from "kiru/router"
import * as __mw_0 from "./pages/guarded/middleware"

export { routes, type PageRoute }

type PageRoute =
  | "/"
  | "/about"
  | "/guarded"

const r0 = createRoute("/", () => import("./pages/page")),
  r1 = createRoute("/about", () => import("./pages/about/page")),
  r3 = createRoute("/guarded", () => import("./pages/guarded/page")),
  r2 = createRouteScope({
    middleware: collectRouteMiddlewareModule(__mw_0),
    children: [r3],
  }),
  routes = createRouteTree({
    layout: () => import("./pages/layout"),
    children: [r0, r1, r2],
  })
