/**
* @generated by vite-plugin-kiru — do not edit
*/
import {
  collectRouteMiddlewareModule,
  createRoute,
  createRouteScope,
  createRouteTree,
} from "kiru/router"
import * as __mw_0 from "./pages/guarded/middleware"

const r0 = createRoute("/", () => import("./pages/page"))
const r1 = createRoute("/about", () => import("./pages/about/page"))
const r3 = createRoute("/guarded", () => import("./pages/guarded/page"))
const r2 = createRouteScope({
  middleware: collectRouteMiddlewareModule(__mw_0),
  children: [r3],
})

export const routes = createRouteTree({
  layout: () => import("./pages/layout"),
  children: [r0, r1, r2],
})

declare module "kiru/router" {
  interface RouteTree {
    routes: [typeof r0, typeof r1, typeof r3]
  }
}
