export default function AboutPage() {
  return (
    <div className="space-y-3">
      <h2 className="text-xl font-semibold text-slate-900">About</h2>
      <p className="text-slate-700">This page is generated by SSG.</p>
      <p className="text-sm text-slate-500">
        Tailwind utility classes are compiled at build time with v4.
      </p>
    </div>
  )
}
