/**
 * @generated by vite-plugin-kiru — do not edit
 */
import { createRoute, createRouteScope, createRouteTree } from "kiru/router"
import { extendRoutes } from "./routes.extend"

export { routes, type AppRoute }

type AppRoute =
  | "/"
  | "/pricing"
  | "/about"
  | "/blog/[slug]"
  | "/docs/[...slug]"
  | "/guarded"
  | "/manual"
  | (typeof extendRoutes)[number]["path"]

const routes = createRouteTree({
  layout: () => import("./pages/layout"),
  notFound: () => import("./pages/not-found"),
  children: [
    createRoute("/", () => import("./pages/page")),
    createRoute("/pricing", () => import("./pages/(marketing)/pricing/page")),
    createRoute("/about", {
      config: () => import("./pages/about/page.config"),
      component: () => import("./pages/about/page"),
    }),
    createRoute("/blog/[slug]", () => import("./pages/blog/[slug]/page")),
    createRoute("/docs/[...slug]", () => import("./pages/docs/[...slug]/page")),
    createRouteScope({
      config: () => import("./pages/guarded/scope.config"),
      children: [createRoute("/guarded", () => import("./pages/guarded/page"))],
    }),
    createRoute("/manual", () => import("./pages/manual/page")),
    ...extendRoutes,
  ],
})

declare module "kiru/router" {
  interface RouteTree {
    routes: AppRoute
  }
}
