import { createRenderer, type CreateRendererOptions } from "kiru/router"
import type { CustomRequestContext } from "kiru/router"
import { matchRoute, generatePublicStaticPaths } from "kiru/router"
import { resolvePathPolicy } from "kiru/router"
import { tryServeImmutablePrerender } from "./serveImmutablePrerender.js"
import { isStaticAssetPathname } from "@kirujs/runtime"

export type GetAssetFn = (
  /** URL pathname, e.g. `/docs` or `/docs.html` */
  pathname: string
) => Promise<string | null>

export type CreateKiruWorkerHandlerOptions = Omit<
  CreateRendererOptions,
  "htmlTemplate" | "prerenderedHtmlDir" | "prerenderCache" | "deployTarget"
> & {
  htmlTemplate: string
  /**
   * Read prerendered HTML from Workers Assets / KV / R2.
   * Receives pathname; return file contents or null.
   */
  getAsset: GetAssetFn
  getRequestContext?: (
    request: Request
  ) => CustomRequestContext | Promise<CustomRequestContext>
  /**
   * Forward hashed bundles and other static files to the Assets binding.
   * Required when `run_worker_first = true` in wrangler.toml.
   */
  assetFetch?: (request: Request) => Promise<Response>
}

export type KiruWorkerHandler = (
  request: Request,
  env?: unknown,
  ctx?: ExecutionContext
) => Promise<Response>

/**
 * Cloudflare Worker `fetch` handler — SSR + immutable static HTML only (no ISR).
 */
export function createKiruWorkerHandler(
  options: CreateKiruWorkerHandlerOptions
): KiruWorkerHandler {
  const {
    getAsset,
    getRequestContext,
    htmlTemplate,
    stream,
    assetFetch,
    ...rendererOpts
  } = options
  const pathPolicy = resolvePathPolicy(rendererOpts.pathPolicy)

  const rendererCommon = {
    ...rendererOpts,
    deployTarget: "cloudflare" as const,
    htmlTemplate,
  }
  const renderer = stream
    ? createRenderer({ ...rendererCommon, stream: true })
    : createRenderer(rendererCommon)

  const getStaticPathSet = () =>
    generatePublicStaticPaths(
      renderer.manifest,
      pathPolicy,
      undefined,
      undefined
    ).then((paths) => new Set(paths))

  const loadPageModule = async (pathname: string) => {
    const match = matchRoute(renderer.manifest, pathname, pathPolicy)
    if (!match) return {}
    return match.route.component()
  }

  return async (request: Request) => {
    const url = new URL(request.url)
    if (assetFetch && isStaticAssetPathname(url.pathname)) {
      return assetFetch(request)
    }

    const context = getRequestContext
      ? await getRequestContext(request)
      : undefined

    const prerendered = await tryServeImmutablePrerender(
      request,
      request.url,
      {
        stream: stream === true,
        getAsset: async (pathname) => {
          const html =
            (await getAsset(pathname)) ??
            (await getAsset(
              pathname.endsWith(".html") ? pathname : `${pathname}.html`
            ))
          if (html) return html
          const indexPath = pathname.endsWith("/")
            ? `${pathname}index.html`
            : `${pathname}/index.html`
          return getAsset(indexPath)
        },
        loadPageModule,
        getStaticPathSet,
        actionsSecret: rendererOpts.actions?.secret,
      },
      { context }
    )

    if (prerendered) {
      const { status, headers, body } = prerendered.result
      return new Response(body as unknown as BodyInit, { status, headers })
    }

    const rendered = await renderer.render(request, { context })
    if (!rendered) {
      return new Response("Not Found", { status: 404 })
    }
    const { status, headers, body } = rendered
    return new Response(body as unknown as BodyInit, { status, headers })
  }
}

/**
 * Wrap a Workers Assets binding as {@link GetAssetFn}.
 */
export function assetsBindingToGetAsset(
  fetchAsset: (request: Request) => Promise<Response>
): GetAssetFn {
  return async (pathname) => {
    const path = pathname.startsWith("/") ? pathname : `/${pathname}`
    const filePath =
      path.endsWith(".html") || path.includes(".")
        ? path
        : `${path.replace(/\/$/, "") || ""}/index.html`.replace(/^\//, "/")
    const url = `https://assets.local${filePath}`
    const res = await fetchAsset(new Request(url))
    if (!res.ok) return null
    return res.text()
  }
}

export type WranglerSnippetOptions = {
  name: string
  main?: string
  assetsDirectory?: string
}

/** Minimal wrangler.toml fragment for documentation / codegen. */
export function generateWranglerSnippet(
  options: WranglerSnippetOptions
): string {
  const main = options.main ?? "dist/server/index.js"
  const assets = options.assetsDirectory ?? "dist/client"
  return `# Generated by @kirujs/adapter-cloudflare — adjust bindings as needed
name = "${options.name}"
main = "${main}"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "${assets}"
binding = "ASSETS"
run_worker_first = true
`
}
