/**
* @generated by vite-plugin-kiru — do not edit
*/
import {
  collectRouteMiddlewareModule,
  createRoute,
  createRouteScope,
  createRouteTree,
} from "kiru/router"

const r0 = createRoute("/", () => import("./pages/page"))
const r1 = createRoute("/pricing", () => import("./pages/(marketing)/pricing/page"))
const r2 = createRoute("/blog/[slug]", () => import("./pages/blog/[slug]/page"))
const r3 = createRoute("/docs/[...slug]", () => import("./pages/docs/[...slug]/page"))

export const routes = createRouteTree({
  layout: () => import("./pages/layout"),
  children: [r0, r1, r2, r3],
})

declare module "kiru/router" {
  interface RouteTree {
    routes: [typeof r0, typeof r1, typeof r2, typeof r3]
  }
}
