/**
 * @generated by vite-plugin-kiru — do not edit
 */
import { createRoute, createRouteTree } from "kiru/router"

export { routes, type AppRoute }

type AppRoute = "/" | "/pricing" | "/blog/[slug]" | "/docs/[...slug]"

const routes = createRouteTree({
  layout: () => import("./pages/layout"),
  children: [
    createRoute("/", () => import("./pages/page")),
    createRoute("/pricing", () => import("./pages/(marketing)/pricing/page")),
    createRoute("/blog/[slug]", () => import("./pages/blog/[slug]/page")),
    createRoute("/docs/[...slug]", () => import("./pages/docs/[...slug]/page")),
  ],
})
