/**
* @generated by vite-plugin-kiru — do not edit
*/
import {
  createRoute,
  createRouteTree,
} from "kiru/router"

export { routes, type PageRoute }

type PageRoute =
  | "/"
  | "/pricing"
  | "/blog/[slug]"
  | "/docs/[...slug]"

const r0 = createRoute("/", () => import("./pages/page")),
  r1 = createRoute("/pricing", () => import("./pages/(marketing)/pricing/page")),
  r2 = createRoute("/blog/[slug]", () => import("./pages/blog/[slug]/page")),
  r3 = createRoute("/docs/[...slug]", () => import("./pages/docs/[...slug]/page")),
  routes = createRouteTree({
    layout: () => import("./pages/layout"),
    children: [r0, r1, r2, r3],
  })
