/**
* @generated by vite-plugin-kiru — do not edit
*/
import {
  collectRouteMiddlewareModule,
  createRoute,
  createRouteScope,
  createRouteTree,
} from "kiru/router"
import * as __cfg_0 from "./pages/about/page.config"
import * as __cfg_1 from "./pages/admin/scope.config"

const __cfg_0_export = __cfg_0.default ?? __cfg_0.config
const __cfg_1_export = __cfg_1.default ?? __cfg_1.config

const r0 = createRoute("/", () => import("./pages/page"))
const r1 = createRoute("/about", {
  ...__cfg_0_export,
  component: () => import("./pages/about/page"),
})
const r3 = createRoute("/admin", () => import("./pages/admin/page"))
const r2 = createRouteScope({
  ...__cfg_1_export,
  children: [r3],
})

export const routes = createRouteTree({
  children: [r0, r1, r2],
})

declare module "kiru/router" {
  interface RouteTree {
    routes: [typeof r0, typeof r1, typeof r3]
  }
}
