/**
 * @generated by vite-plugin-kiru — do not edit
 */
import { createRoute, createRouteScope, createRouteTree } from "kiru/router"

export { routes, type AppRoute }

type AppRoute = "/" | "/about" | "/admin"

const routes = createRouteTree({
  children: [
    createRoute("/", () => import("./pages/page")),
    createRoute("/about", {
      config: () => import("./pages/about/page.config"),
      component: () => import("./pages/about/page"),
    }),
    createRouteScope({
      config: () => import("./pages/admin/scope.config"),
      children: [createRoute("/admin", () => import("./pages/admin/page"))],
    }),
  ],
})
