export type WranglerSnippetOptions = {
  name: string
  main?: string
  assetsDirectory?: string
}

/** Minimal wrangler.toml fragment (duplicated from @kirujs/adapter-cloudflare to avoid bundling kiru into the plugin). */
export function generateWranglerSnippet(options: WranglerSnippetOptions): string {
  const main = options.main ?? "dist/server/index.js"
  const assets = options.assetsDirectory ?? "dist/client"
  return `# Generated by vite-plugin-kiru — review and copy to wrangler.toml
name = "${options.name}"
main = "${main}"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "${assets}"
binding = "ASSETS"
run_worker_first = true
`
}
